# Generated by Django 6.0.1 on 2026-02-04 22:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата оплаты"
            ),
        ),
    ]
