[tool.poetry]
name = "homework-7"
version = "0.1.0"
description = ""
authors = ["Vladislav Lukin <vladislavlukin090392@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django = "^6.0.1"
djangorestframework = "^3.16.1"
pillow = "^12.1.0"
psycopg2-binary = "^2.9.11"
dotenv = "^0.9.9"
docutils = "^0.22.4"
django-filter = "^25.2"
djangorestframework-simplejwt = "^5.5.1"
drf-yasg = "^1.21.15"
stripe = "^15.1.0"
celery = "^5.6.3"
eventlet = "^0.41.0"
redis = "^7.4.0"
django-celery-beat = "^2.9.0"
gunicorn = "^26.0.0"
flake8 = "^7.3.0"


[tool.poetry.group.dev.dependencies]
black = "^26.3.1"
isort = "^8.0.1"
coverage = "^7.13.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
